---
name: Net-LastFM-Submission
version: 0.3
author:
  - 'Anatoly Sharifulin <sharifulin@gmail.com>'
abstract: Perl interface to the Last.fm Submissions Protocol
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Carp: 0
  Digest::MD5: 0
  Encode: 0
  HTTP::Request::Common: 0
  LWP::UserAgent: 0
  perl: 5.008
build_requires:
  Test::More: 0
provides:
  Net::LastFM::Submission:
    file: lib/Net/LastFM/Submission.pm
    version: 0.3
generated_by: Module::Build version 0.2807
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
