---
name: Net-LastFM-Submission
version: 0.63
author:
  - 'Anatoly Sharifulin <sharifulin@gmail.com>'
abstract: Perl interface to the Last.fm Submissions Protocol
license: perl
resources:
  license: http://dev.perl.org/licenses/
  repository: http://github.com/sharifulin/net-lastfm-submission/tree
requires:
  Carp: 0
  Digest::MD5: 0
  Encode: 0
  Exporter: 0
  HTTP::Request::Common: 0
  LWP::UserAgent: 0
  POE: 0
  POE::Component::Client::HTTP: 0
  perl: 5.008
build_requires:
  Encode: 0
  HTTP::Response: 0
  LWP::UserAgent: 0
  Test::Exception: 0
  Test::More: 0
provides:
  Net::LastFM::Submission:
    file: lib/Net/LastFM/Submission.pm
    version: 0.63
  POE::Component::Net::LastFM::Submission:
    file: lib/POE/Component/Net/LastFM/Submission.pm
    version: 0.24
generated_by: Module::Build version 0.280801
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
keywords:
  - last.fm
  - submission
